import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default styles = StyleSheet.create({
  appScrollView: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
  },
  appView: {
    alignItems: 'center',
    width:'100%',
  },
  aboutMe: {
    backgroundColor: '#ffffff',
    height: 770,
    width: 1432,
    position: 'relative',
  },
  header: {
    position: 'absolute',
    top: 12,
    left: 0,
    width: 1432,
    height: 62,
    backgroundColor: '#ffffff',
    borderRadius: 0,
  },
  headerTitle: {
    flex:1,
    position: 'absolute',
    left: 100,
    fontFamily: 'Archivo',
    fontSize: 30,
    padding:20,
    fontWeight: 700,
    color: '#171A1F',
  },
  headerMenu: {
    position: 'absolute',
    top: 10,
    width: 384,
    right: 150,
    flexDirection: 'row',
    fontFamily: 'Inter',
    fontSize: 14,
    lineHeight: 22,
    fontWeight: 400,
    opacity: 1,
  },
  headerMenuItem: {
    padding: 20,
  },
  headerMenuItemSelectedText: {
    fontFamily: 'Inter',
    fontSize: 14,
    lineHeight: 22,
    fontWeight: 800,
    position: 'relative',
    color: '#636AE8',
  },
  headerMenuItemText: {
    fontFamily: 'Inter',
    fontSize: 14,
    lineHeight: 22,
    fontWeight: 400,
    color: '#424955FF', // neutral-650
  },
  profileImage: {
    backgroundColor: '#d9d9d9',
    borderEndStartRadius: 300,
    borderBottomEndRadius: 300,
    height: 643,
    width: 482,
    position: 'absolute',
    top: 100,
    right: 100,
  },
  content: {
    position: 'absolute',
    top: 321,
    left: 128,
    width: 483,
  },
  greeting: {
    color: '#323842',
    fontFamily: 'Archivo-Regular',
    fontSize: 52,
    lineHeight: 74,
  },
  description: {
    color: '#323842',
    fontFamily: 'Archivo-Regular',
    fontSize: 20,
    lineHeight: 30,
  },
  //blog
  blog: {
    backgroundColor: '#ffffff',
    borderWidth: 0,
    height: 561,
    position: 'relative',
    width: 1440,
    justifyContent: 'space-around',
  },
  blogTabMenu: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 10,
    height: 52,
    width: 1075,
    left: 176,
    position: 'absolute',
    top: 64,
  },
  blogTab: {
    alignItems: 'center',
    padding: 10,
    width: 200,
    cursor: 'pointer'
  },
  blogTabText: {
    color: '#565e6c',
    fontFamily: 'Inter-Reguler', 
    fontSize: 14,
    fontWeight: 400,
  },
  blogTabActive : {
    borderBottomColor: '#636AE8',
    borderBottomWidth: 4,
  },
  blogTabIcon: {
    height: 24,
    width: 24,
    marginRight: 5,
    tintColor: '#fffffff'
  },
  blogDateTextWrapper: {
    color: '#323842',
    fontFamily: 'Inter-Regular',
    fontSize: 14,
    fontWeight: '400',
    right: 200,
    letterSpacing: 0,
    lineHeight: 22,
    position: 'absolute',
    textAlign: 'right',
    top: 430,
    width: 109,
  },
  blogImage: {
    height: 300,
    left: 158,
    position: 'absolute',
    top: 165,
    width: 450,
    margin: 5,
    borderRadius: 12,
  },

  //Mark: Button
  customButton: {
    backgroundColor: '#636ae8',
    borderWidth: 1,
    borderColor: 'transparent',
    borderRadius: 18,
    height: 36,
    overflow: 'hidden',
    position: 'relative',
    width: 120,
    top: 400,
    left: 680,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonTextWrapper: {
    color: '#ffffff',
    fontFamily: 'Inter-Regular',
    fontSize: 14,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 22,
    position: 'absolute',
    left: 39,
    top: 8,
  },
  arrowRight: {
    height: 16,
    width: 16,
    position: 'absolute',
    left: 17,
    top: 10,
  },
  arrowRight: {
    height: 16,
    left: 17,
    position: 'absolute',
    top: 10,
    width: 16,
  },
  forAgencyEnhance: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontSize: 20,
    fontWeight: '400',
    left: 695,
    letterSpacing: 0,
    lineHeight: 30,
    position: 'absolute',
    top: 168,
    width: 608,
  },
  //project
  projects: {
    backgroundColor: '#ffffff',
    borderWidth: 0,
    flex:1,
    height: 770,
    position: 'relative',
    width: 1440,
  },
  projectTitle: {
    fontSize: 50,
    fontFamily: 'Archivo-Regular',
    left:128,
    top:0,
    marginBottom: 0,
  },
  projectDescription: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontSize: 20,
    position:'absolute',
    left:700,
    letterSpacing: 0,
    top:20,
    width: 572,
  },
  projectImageGridContainer: {
    flex:1,
    flexDirection: 'row',
    left: 105,
    top: 20,
  },
  projectImageRow: {
    flex:2,
    flexDirection: 'row',
  },
  projectImageColumn: {
    flex:3,
    flexDirection: 'column',
  },
  imageP1: {
    flex:3,
    height: 570,
    borderRadius: 12,
    margin:5,
  },
  imageP2: {  
    flex:3,
    height: 570,
    borderRadius: 12,
    margin:5,
  },
  imageP3: {
    flex:3,
    width: 570,
    height: 275,
    borderRadius: 12,
    margin:5,
  },
  imageP4: {
    flex:3,
    width: 570,
    height: 275,
    borderRadius: 12,
    margin:5,
  },
  // calender
  calendar: {
    backgroundColor: '#fafafa',
    height: 331,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    maxWidth: 1440,
    margin: '0 auto',
    padding: 20,
    borderRadius: 0,
  },
  calendarTitle: {
    color: '#636ae8',
    fontFamily: 'Archivo',
    fontSize: 48,
    fontWeight: '400',
    textAlign: 'center',
    marginBottom: 20,
  },
  calendarDescription: {
    color: '#171a1f',
    fontFamily: 'Inter',
    fontSize: 18,
    fontWeight: '400',
    textAlign: 'center',
    marginBottom: 30,
    maxWidth: 912,
  },
  calendarButton: {
    backgroundColor: '#636ae8',
    borderRadius: 6,
    height: 52,
    width: 178,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  calendarButtonText: {
    color: '#ffffff',
    fontFamily: 'Inter',
    fontSize: 18,
    fontWeight: '400',
  },
  //contact
  contactContainer: {
    flex: 1,
    padding: 40,
    height: 400,
    backgroundColor: '#000',
  },
  sayHelloText: {
    color: '#ffffff',
    fontFamily: 'Archivo-Regular',
    fontSize: 52,
    fontWeight: '400',
    lineHeight: 74,
    position: 'absolute',
    top: 23,
    left: 132,
    width: 466,
  },
  emailTextbox: {
    height: 74,
    position: 'absolute',
    top: 23,
    left: 720,
    width: 588,
  },
  emailOverlap: {
    height: 74,
    position: 'relative',
    top: -1,
    width: 587,
  },
  emailOverlapGroupWrapper: {
    borderRadius: 0,
    height: 59,
    position: 'absolute',
    top: 25,
    width: 587,
  },
  emailOverlapGroup: {
    backgroundColor: '#fff',
    borderRadius: 6,
    height: 61,
    position: 'relative',
    width: 589,
  },
  textWrapperEmail: {
    color: '#bcc1ca',
    fontFamily: 'Inter-Regular',
    fontSize: 18,
    fontWeight: '400',
    position: 'absolute',
    top: 15,
    left: 0,
  },
  emailLabel: {
    color: '#ffffff',
    fontFamily: 'Inter-Regular',
    fontSize: 18,
    fontWeight: '400',
    position: 'absolute',
    top: 0,
    left: 6,
  },
  descriptionTextbox: {
    height: 135,
    position: 'absolute',
    top: 121,
    left: 720,
    width: 588,
  },
  descriptionOverlap: {
    height: 135,
    position: 'relative',
    top: -1,
    width: 587,
  },
  descriptionOverlapGroupWrapper: {
    borderRadius: 0,
    height: 120,
    position: 'absolute',
    top: 25,
    width: 587,
  },
  descriptionOverlapGroup: {
    backgroundColor: '#fff',
    borderRadius: 6,
    height: 122,
    position: 'relative',
    width: 589,
  },
  descriptionTextWrapper: {
    color: '#bcc1ca',
    fontFamily: 'Inter-Regular',
    fontSize: 18,
    fontWeight: '400',
    position: 'absolute',
    top: 11,
    left: 16,
    width: 548,
  },
  resizingHandle: {
    height: 12,
    position: 'absolute',
    top: 106,
    left: 573,
  },
  textWrapperMessage: {
    color: '#ffffff',
    fontFamily: 'Inter-Regular',
    fontSize: 18,
    fontWeight: '400',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  contactButton: {
    backgroundColor: '#636ae8',
    borderRadius: 6,
    height: 52,
    position: 'absolute',
    top: 280,
    left: 720,
    width: 173,
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitTextWrapper: {
    color: '#ffffff',
    fontFamily: 'Inter-Regular',
    fontSize: 18,
    fontWeight: '400',
  },
  logoInstagram: {
    height: 24,
    position: 'absolute',
    top: 274,
    left: 132,
    width: 24,
  },
  dribbbleLogo: {
    height: 24,
    position: 'absolute',
    top: 274,
    left: 192,
    width: 24,
  },
  linkedinLogo: {
    height: 24,
    position: 'absolute',
    top: 274,
    left: 252,
    width: 24,
  },
  envelopeOpen: {
    height: 24,
    position: 'absolute',
    top: 274,
    left: 312,
    width: 24,
  },
  contactOverlapFooter: {
    height: 22,
    position: 'absolute',
    top: 310,
    left: 329,
    width: 60,
  },
  sitemapTextWrapper: {
    color: '#ffffff',
    fontFamily: 'Inter-Regular',
    fontSize: 14,
    fontWeight: '400',
    position: 'absolute',
    top: 0,
    left: 6,
  },
  yearTextWrapper: {
    color: '#ffffff',
    fontFamily: 'Inter-Regular',
    fontSize: 14,
    fontWeight: '400',
    position: 'absolute',
    top: 310,
    left: 126,
  },
  privacyTextWrapper: {
    color: '#ffffff',
    fontFamily: 'Inter-Regular',
    fontSize: 14,
    fontWeight: '400',
    position: 'absolute',
    top: 310,
    left: 205,
  },
  termsTextWrapper: {
    color: '#ffffff',
    fontFamily: 'Inter-Regular',
    fontSize: 14,
    fontWeight: '400',
    position: 'absolute',
    top: 310,
    left: 273,
  },
});

