import { height, padding, textAlign } from '@mui/system';
import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

// Define a static font family
const FONT_FAMILY = 'Areal';

export default styles = StyleSheet.create({
  appScrollView: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
  },
  appView: {
    alignItems: 'center',
    width: '100%',
  },
  header: {
    width: '100%',
    backgroundColor: '#ffffff',
    margin: 20,
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-around',
    flexWrap: 'wrap',
  },
  headerTitle: {
    fontFamily: FONT_FAMILY,
    fontSize: width > 768 ? 50 : 30,
    fontWeight: '400',
    color: '#171A1F',
    textAlign: width > 375 ? 'left' : 'center',
    padding: 30,
    alignContent: 'center',
    textAlign: 'center',
  },
  headerMenu: {
    marginTop: 20,
    padding: 20,
    flexDirection: width > 375 ? 'row' : 'column',
    justifyContent: 'space-around',
    width: width > 768 ? '50%' : '100%',
    flexWrap: 'wrap',
    alignContent: width > 768 ? 'flex-start' : 'center',
  },
  headerMenuItem: {
    padding: 10,
    margin: 10,
  },
  headerMenuItemSelectedText: {
    fontFamily: FONT_FAMILY,
    fontSize: width > 768 ? 14 : 10,
    fontWeight: '1000',
    color: '#636AE8', // primary-500
  },
  headerMenuItemText: {
    fontFamily: FONT_FAMILY,
    fontSize: width > 768 ? 14 : 10,
    fontWeight: '400',
  },
  content: {
    width: '100%',
  },
  aboutMe: {
    backgroundColor: '#ffffff',
    padding: 20,
    width: '90%',
    maxWidth: 1200,
    marginVertical: 20,
    flexWrap: 'wrap',
  },
  aboutMeContent: {
    width: '100%',
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    flexWrap: 'wrap',
    alignContent: 'center',
  },
  aboutMeIntro: {
    width: '60%',
    justifyContent: 'center',
    padding: 10,
    flexDirection: 'column',
    flexWrap: 'nowrap',
  },
  greeting: {
    color: '#323842',
    margin: 10,
    fontFamily: FONT_FAMILY,
    fontSize: width > 768 ? 40 : 20,
    textAlign: 'justify-left',
    flexWrap: 'wrap',
  },
  description: {
    margin: 10,
    fontFamily: FONT_FAMILY,
    fontSize: width > 768 ? 16 : 8,
    textAlign: width > 768 ? 'left' : 'left',
    textAlign: 'justify-left',
  },
  profileImage: {
    marginVertical: 20,
    width: '30%',
    height: '50%',
    aspectRatio: 2/3, // Maintain aspect ratio
    resizeMode: 'cover', // Scale down image
    borderEndStartRadius: width * 0.5,
    borderBottomEndRadius: width * 0.5,
  },
  // Blog styles
  blog: {
    backgroundColor: '#ffffff',
    padding: 20,
    width: '100%',
    maxWidth: 1200,
    height: 'auto',
    flexWrap: 'wrap',
  },
  blogTabMenu: {
    width: 'auto',
    height: 'auto',
    flexDirection: 'row',
    alignContent: 'center',
    justifyContent: 'space-around',
  },
  blogTab: {
    width: width > 768 ? 200 : 'auto',
    padding: 5,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    flexWrap: 'nowrap',
  },
  blogTabActive: {
    borderBottomColor: '#636ae8',
    borderBottomWidth: 4,
    borderEndStartRadius: 3,
    borderBottomEndRadius: 3,
  },
  blogTabIcon: {
    height: 20,
    width: 20,
    justifyContent: 'center',
    alignContent: 'center',
    tintColor: '#636ae8',
  },
  blogTabText: {
    margin: 5,
    color: '#636ae8',
    fontFamily: FONT_FAMILY,
    textAlign: 'center',
    alignContent: 'center',
  },
  blogContent: {
    width: '100%',
    marginTop: 20,
    marginBottom: 20,
    padding: width > 768 ? 20 : 15,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    flexWrap: 'wrap',
  },
  blogImage: {
    width: '40%',
    margin: width > 768 ? 10 : 5,
    resizeMode: 'cover', // Scale down image
    aspectRatio: 3/2,
    height: '30%', // Ensure auto height
    borderRadius: 12,
  },
  blogTextContent: {
    width: '50%',
    padding: width > 768 ? 10 : 5,
    margin: width > 768 ? 10 : 5,
    flexDirection: 'column',
    flexWrap: 'wrap',
    alignContent: 'left',
  },
  blogTitle: {
    color: '#323842',
    margin: width > 768 ? 10 : 5,
    fontFamily: FONT_FAMILY,
    fontSize: width > 768 ? 30 : 15,
  },
  blogDescriptionText: {
    color: '#000000',
    margin: width > 768 ? 10 : 5,
    width: '90%',
    fontFamily: FONT_FAMILY,
    textAlign: 'justify-left',
    fontSize: width > 768 ? 15 : 7,
    left: 'auto',
  },
  blogButton: {
    margin: width > 768 ? 10 : 5,
    padding: 10,
    backgroundColor: '#636ae8',
    height: width > 768 ? 40 : 10,
    width: width > 768 ? 120 : 100,
    aspectRatio: 4/1,
    fontFamily: FONT_FAMILY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'left',
    borderRadius: 5,
  },
  buttonTextWrapper: {
    color: '#ffffff',
    fontFamily: FONT_FAMILY,
    fontSize: width > 768 ? 10 : 8,
  },
  arrowRight: {
    height: 14,
    width: 14,
    marginLeft: 10,
  },
  
  //project
  projects: {
    backgroundColor: '#ffffff',
    padding: 20,
    width: '100%',
    maxWidth: 1200,
    marginVertical: 20,
    flexWrap: 'nowrap',
  },
  projectHeader: {
    width: '100%',
    padding: 20,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  projectTitle: {
    width: '40%',
    fontWeight: '800',
    fontSize: width > 768 ? 30 : 15,
    fontFamily: FONT_FAMILY,
    alignContent: 'flex-end',
  },
  projectDescription: {
    width: '60%',
    padding: 10,
    marginLeft: 'auto',
    fontFamily: FONT_FAMILY,
    fontSize: width > 768 ? 16 : 8,
    textAlign: 'justify',
  },
  projectImageGridContainer: {
    padding: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
  },
  projectImageRowGrid: {
    width: '40%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
  },
  projectImageColumnGrid: {
    width: '60%',
    flexDirection: 'column',
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
  },
  imageRow: {
    flex: 3,
    margin: 10,
    width: '15%',
    height: width > 768 ? 560 : 200,
    justifyContent: 'space-evenly',
    borderRadius: 12,
  },
  imageColumn: {
    flex:3,
    margin:10,
    width: 'auto',
    height: 'auto',
    aspectRatio: 1,
    justifyContent: 'space-evenly',
    borderRadius: 12,
  },
  //contact
  contactContainer: {
    width: '100%',
    maxWidth: 1200,
    backgroundColor: '#1D2128',
    padding: 20,
  },
  contactView: {
    width: '100%',
    padding: 20,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignContent: 'center',
    flex: 3,
  },
  sayHelloView: {
    width: '50%',
    flexDirection: 'column',
    justifyContent: 'space-around',
  },
  sayHelloText: {
    color: '#ffffff',
    fontFamily: FONT_FAMILY,
    padding: 20,
    fontSize: width > 768 ? 46 : 23,
    height: 150,
    justifyContent: 'center',
    textAlign: 'left',
    fontWeight: '400',
  },
  emailViewContainer: {
    width: '40%',
    height: 'auto',
    marginLeft: 10,
    flex: 3,
  },
  emailTextbox: {
    backgroundColor: '#fff',
    marginTop: 10,
    height: 50,
    borderRadius: 6,
    padding: 10,
    marginBottom: 20,
  },
  descriptionTextbox: {
    backgroundColor: '#fff',
    height: 150,
    borderRadius: 6,
    padding: 10,
    marginBottom: 20,
  },
  emailOverlap: {
    height: 74,
    position: 'relative',
    top: -1,
    width: 587,
  },
  emailOverlapGroupWrapper: {
    borderRadius: 0,
    height: 59,
    position: 'absolute',
    top: 25,
    width: 587,
  },
  emailOverlapGroup: {
    backgroundColor: '#fff',
    borderRadius: 6,
    height: 60,
    position: 'relative',
    width: 589,
  },
  textWrapperEmail: {
    color: '#bcc1ca',
    fontFamily: FONT_FAMILY,
    fontSize: width > 768 ? 20 : 12,
    fontWeight: '400',
    position: 'absolute',
    top: 15,
    left: 15,
  },
  emailLabel: {
    color: '#ffffff',
    fontFamily: FONT_FAMILY,
    fontSize: 18,
    fontWeight: '400',
    marginBottom: 10,
  },
  descriptionTextWrapper: {
    color: '#bcc1ca',
    fontFamily: FONT_FAMILY,
    fontSize: width > 768 ? 20 : 12,
    fontWeight: '400',
    position: 'absolute',
    top: 11,
    left: 15,
    width: 548,
  },
  descriptionOverlap: {
    height: 135,
    position: 'relative',
    top: -1,
    width: 587,
  },
  descriptionOverlapGroupWrapper: {
    borderRadius: 0,
    height: 120,
    position: 'absolute',
    top: 25,
    width: 587,
  },
  descriptionOverlapGroup: {
    backgroundColor: '#fff',
    borderRadius: 6,
    height: 122,
    position: 'relative',
    width: 589,
  },
 
  resizingHandle: {
    height: 12,
    position: 'absolute',
    top: 106,
    left: 573,
  },
  textWrapperMessage: {
    color: '#ffffff',
    fontFamily: FONT_FAMILY,
    fontSize: 18,
    fontWeight: '400',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  contactButtonView: {
    backgroundColor: '#ffffff',
    borderRadius: 6,
    width: width > 768 ? 178 : 75,
    alignItems: 'left',
  },
  contactButton: {
    backgroundColor: '#636ae8',
    borderRadius: 6,
    height: width > 768 ? 50 : 30,
    width: width > 768 ? 178 : 75,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitTextWrapper: {
    color: '#ffffff',
    fontFamily: FONT_FAMILY,
    fontSize: width > 768 ? 18 : 9,
    fontWeight: '400',
  },
  logoInstagram: {
    height: 24,
    position: 'absolute',
    top: 274,
    left: 132,
    width: 24,
  },
  dribbbleLogo: {
    height: 24,
    position: 'absolute',
    top: 274,
    left: 192,
    width: 24,
  },
  linkedinLogo: {
    height: 24,
    position: 'absolute',
    top: 274,
    left: 252,
    width: 24,
  },
  envelopeOpen: {
    height: 24,
    position: 'absolute',
    top: 274,
    left: 312,
    width: 24,
  },
  contactOverlapFooter: {
    height: 22,
    position: 'absolute',
    top: 310,
    left: 329,
    width: 60,
  },
  sitemapTextWrapper: {
    color: '#ffffff',
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: '400',
    position: 'absolute',
    top: 0,
    left: 6,
  },
  yearTextWrapper: {
    color: '#ffffff',
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: '400',
    position: 'absolute',
    top: 310,
    left: 126,
  },
  privacyTextWrapper: {
    color: '#ffffff',
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: '400',
    position: 'absolute',
    top: 310,
    left: 205,
  },
  termsTextWrapper: {
    color: '#ffffff',
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: '400',
    position: 'absolute',
    top: 310,
    left: 273,
  },
  socialIcons: {
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 20,
    alignContent: 'center',
    alignItems: 'center',
  },
  socialIcon: {
    height: 30,
    width: 30,
  },
  xIcon: {
    width: 20,
    height: 20,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  footerText: {
    color: '#ffffff',
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: '400',
  },
  // calender
  calendar: {
    backgroundColor: '#fafafa',
    padding: 20,
    width: '90%',
    maxWidth: 1200,
    marginVertical: 20,
    alignItems: 'center',
  },
  calendarTitle: {
    color: '#636ae8',
    fontFamily: FONT_FAMILY,
    fontSize: 32,
    fontWeight: '400',
    textAlign: 'center',
    marginBottom: 20,
  },
  calendarDescription: {
    color: '#171a1f',
    fontFamily: FONT_FAMILY,
    fontSize: 16,
    fontWeight: '400',
    textAlign: 'center',
    marginBottom: 30,
  },
  calendarButton: {
    backgroundColor: '#636ae8',
    borderRadius: 6,
    height: 52,
    width: 178,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarButtonText: {
    color: '#ffffff',
    fontFamily: FONT_FAMILY,
    fontSize: 18,
    fontWeight: '400',
  },

  popUpcontainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  popup: {
    backgroundColor: 'white',
    padding: width > 768 ? 40 : 20,
    borderRadius: 30,
    width: width > 768 ? '30%' : '80%',
    alignItems: 'center',
    maxWidth: 500, // Prevent popup from getting too wide on large screens
  },
  title: {
    fontSize: width > 768 ? 24 : 18,
    fontWeight: 'bold',
    fontFamily: FONT_FAMILY,
    marginBottom: width > 768 ? 20 : 15,
    textAlign: 'center',
  },
  input: {
    width: '100%',
    height: width > 768 ? 50 : 40,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 30,
    paddingHorizontal: width > 768 ? 20 : 15,
    marginBottom: width > 768 ? 15 : 10,
    fontSize: width > 768 ? 18 : 16,
  },
  error: {
    color: 'red',
    marginBottom: width > 768 ? 15 : 10,
    fontFamily: FONT_FAMILY,
    fontSize: width > 768 ? 16 : 14,
    textAlign: 'center',
  },
  button: {
    backgroundColor: '#007AFF',
    padding: width > 768 ? 15 : 12,
    borderRadius: 30,
    width: '100%',
    alignItems: 'center',
  },
  buttonText: {
    color: 'white',
    fontSize: width > 768 ? 18 : 16,
    fontWeight: 'bold',
    fontFamily: FONT_FAMILY,
  },
  welcomeImage: {
    width: '100%',
    height: width > 768 ? 200 : 150,
    marginBottom: width > 768 ? 30 : 20,
    maxHeight: 250, // Prevent image from getting too tall
  },
});

